name: workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'readme_images/**'  # if you have images
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          set -e
          echo "Building $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Compute image URI and pull
        id: pull
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        run: |
          set -e
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:latest"
          echo "IMAGE_URI=$IMAGE_URI" >> "$GITHUB_ENV"
          echo "Pulling $IMAGE_URI"
          docker pull "$IMAGE_URI"

      - name: Stop and remove container if running (safe)
        shell: bash
        run: |
          CID="$(docker ps -q -f name=cnncls || true)"
          if [ -n "$CID" ]; then
            echo "Stopping existing cnncls ($CID)…"
            docker stop cnncls || true
            docker rm -fv cnncls || true
          else
            echo "No existing cnncls container."
          fi

      - name: Run Docker Image to serve users
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
          PORT_OUT: 8080
          PORT_IN: 5002
        run: |
          set -e
          echo "Launching $IMAGE_URI on ${PORT_OUT}->${PORT_IN}"
          docker run -d --name cnncls \
            -p ${PORT_OUT}:${PORT_IN} \
            -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -e AWS_REGION='${{ secrets.AWS_REGION }}' \
            --restart unless-stopped \
            "$IMAGE_URI"

      - name: Clean previous images and containers (non-fatal)
        run: docker system prune -f || true
